---
title: "Research"
---

I study maternal-infant health in both contemporary and historical populations. One of my projects studies the effects of food insecurity on maternal-infant health in Senegal. 

In another project, I develop and apply a new indicator for maternal-infant health in historical populations: childhood sex ratios. Using sex-ratio data, we provide new estimates of infant mortality for the 19th-century US.

Broadly speaking, I am interested in the interplay of health and 'development' -- whether in 19th-century North America or 21st-century Senegal.

# Publications

<details class="details-example">
    <summary>  Infant Mortality among US Whites in the 19th Century: New Evidence from Childhood Sex Ratios. 2025. [_Demographic Research_](https://www.demographic-research.org/articles/volume/52/10). </summary>
    <ul>
    _We offer a new empirical basis for characterizing infant mortality: childhood sex ratios. Because males are biologically more vulnerable than females to infant mortality, high rates of infant death tend to be reflected in female-skewed childhood sex ratios. Assembling historical vital statistics and census data, we document a striking relationship between childhood sex ratios and infant mortality. Based on that relationship, we provide new estimates of infant mortality for the nineteenth-century US, a population for whom we lack vital statistics but have rich census data. We find that infant mortality for US whites was roughly 70–80 deaths per 1000 in the mid-nineteenth century._
   </ul>
</details>


<details class="details-example">
    <summary> Child Anemia and the 2008 Food Price Crisis in Senegal. 2024. [_Demographic Research_](https://www.demographic-research.org/articles/volume/51/20). </summary>
    <ul>
    _I estimate the effects of the 2008 food price crisis on child hemoglobin in Senegal. Early-life hemoglobin reflects in-utero iron deposition, making it a bio-marker for maternal malnutrition. By comparing children in-utero during the 2008 crisis to those who were breastfeeding, I develop a quasi-experimental framework to quantify the impact of the 2008 crisis on maternal-infant health. I find large negative impacts of the crisis in urban Senegal, and no impact in rural areas. The effect was largest in Dakar, where it implied a more than doubling of the prevalence childhood anemia, from 1-in-3 children to 3-in-4._
  </ul>
</details>



# Working Papers

<details class="details-example">
    <summary> US Infant Mortality under Slavery and after Emancipation ([_in progress_](https://jrmcirwin.github.io/sr1/UsSlv.pdf)) </summary>
    <ul>
    _I use childhood sex ratios to characterize infant mortality rates among the US Black population 1850–1880, until now a matter of speculation due to a lack of birth and death records. Because of the biological survival advantage of infant females, high rates of infant mortality tend to skew the surviving population toward females. Building on this well-known fact, I use vital statistics data from contemporary Europe to quantify the empirical relationship between infant mortality and childhood sex ratios. Applying this relationship to the 19th century US, I compare infant mortality between the Black and white populations under slavery, and infant mortality among US Blacks before and after emancipation. Circa 1850 to 1860, the infant mortality rate among the Black population was around 300 deaths per 1,000, while the rate among whites was likely below 100. Infant mortality for US Blacks improved substantially after emancipation, dropping nearly 100 points to around 200 deaths per 1000, while white infant mortality remained roughly the same, cutting the Black-white disparity in half._
   </ul>
</details>


<details class="details-example">
    <summary> Childhood Sex Ratios Reveal Infant Mortality ([_in progress_](https://jrmcirwin.github.io/sr1/DemPap_1.pdf))</summary>
    <ul> 
      _We offer a new approach to characterizing broad patterns of infant mortality, using childhood sex ratios. Girls are hardier than boys, with lower rates of infant mortality unless their biological advantage is offset by sex discrimination. Therefore, high levels of infant mortality tend to skew the surviving population toward females. Extremes of male-biased sex ratios are familiar as indicators of missing women, but the potential for sex-ratio data to reveal patterns of infant mortality estimates has gone largely unnoticed. We document the relationship between infant mortality and childhood sex ratios in historical data from Europe and its settler colonies, showing that broad patterns of infant mortality can be inferred from sex-ratio data. Widely available from census data, childhood sex ratios can shed new light on infant mortality and maternal health in populations lacking mortality data._
    </ul>
</details>

