---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Jesse McDevitt-Irwin

jobtitle: "Postdoctoral Scholar, Northwestern University"
address: "2211 Campus Dr · Evanston, IL 60208"
fontawesome: yes
email: jesse.mcdevittirwin@northwestern.edu
updated: yes
web: jrmcirwin.github.io


keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: black
urlcolor: blue
---

# Academic Positions

Northwestern University

> __Postdoctoral Scholar__ at the Center for Economic History  \hfill 2024--2025

> __Lecturer__ in the Economics Department \hfill 2024--2025

University of Chicago

> __Lecturer__ in the Social Sciences Collegiate Division  \hfill 2023--2024

---

# Education

Columbia University

>__Ph.D.__ in Sustainable Development  \hfill 2024

University of British Columbia

>__M.A.__ in Economics \hfill 2017

Queen's University

>__B.A.__ in Applied Economics \hfill 2016

---

# Publications

McDevitt-Irwin, Jesse, and James R. Irwin. 2025. Infant Mortality among US Whites in the 19th Century: New Evidence from Childhood Sex Ratios. Demographic Research, 52, 303-350. ([link](https://www.demographic-research.org/articles/volume/52/10)).

McDevitt-Irwin, Jesse. 2024. Child anemia and the 2008 food price crisis in Senegal. Demographic Research, 51, 637–668 ([link](https://www.demographic-research.org/articles/volume/51/20)).



---

# Working Papers

McDevitt-Irwin, Jesse. US Infant Mortality under Slavery and after Emancipation ([_in progress_](https://jrmcirwin.github.io/sr1/UsSlv.pdf)).

McDevitt-Irwin, Jesse, and James R. Irwin. Childhood Sex Ratios Reveal Infant Mortality  
([_in progress_](https://jrmcirwin.github.io/sr1/DemPap_1.pdf)).


---

# Teaching Experience

Northwestern University, Lecturer \hfill 2025

ECON 323-2 Economic History of the US post 1860

University of Chicago, Lecturer \hfill 2023--2024

SOSC 16300 Global Society-III 

---

# Languages

English  (_native_); French  (_fluent_); Spanish (_B2_); Wolof (_intermediate_)

---

# Awards

SSHRC Doctoral Fellowship \hfill 2021--2023

Wu Fellowship, Columbia University \hfill 2018--2019

Dean's Fellow, Columbia University \hfill 2018-2023

---

# Presentations

Northwestern Economic History Seminar \hfill Oct. 2024

Population Association of America, Annual Meeting \hfill 2023

Northwestern Economic History Workshop \hfill Feb. 2023

University of Chicago Demography Workshop \hfill Jan. 2023

Canadian Economic Association Conference, Canadian Network of Economic History \hfill  2022

Canadian Economic Association Conference, Canadian Network of Economic History \hfill  2021

---

# Affiliations

Center for Economic History, Northwestern University \hfill Spring 2023

West African Research Center, Dakar, Senegal \hfill Fall 2022

---

# Service

Columbia University Sustainable Development Doctoral Society, President \hfill 2020--2021

---

# Selected Work Experience

Kandalore Canoe Company, Carpenter \hfill 2017

Finance Canada, Policy Analyst \hfill 2018

University of British Columbia, Research Assistant \hfill 2017

University of Chicago Harris School of Public Policy, Research Assistant \hfill 2017

